# Generated by Django 5.2.1 on 2025-05-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=30)),
                ('categoria', models.CharField(max_length=100)),
                ('data_cadastro', models.DateField()),
                ('data_emprestimo', models.DateField()),
                ('data_devolucao', models.DateField()),
                ('nome_emprestado', models.CharField(max_length=100)),
                ('tempo_duracao', models.IntegerField()),
            ],
        ),
    ]
